-- Complete PostgreSQL SQL script for tourist_locations table
-- Generated from Samudrayan Tourist Locations.xlsx
-- This script follows the existing database patterns in the codebase

-- Drop table if exists (uncomment if needed)
-- DROP TABLE IF EXISTS tourist_locations;

-- Create tourist_locations table
CREATE TABLE IF NOT EXISTS tourist_locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sr_no INTEGER NOT NULL,
    place_name VARCHAR(255) NOT NULL,
    taluka VARCHAR(100),
    location TEXT,
    latitude_longitude VARCHAR(255),
    video_link TEXT,
    description TEXT,
    famous_for TEXT,
    best_time_to_visit VARCHAR(100),
    ideal_duration VARCHAR(100),
    images_drive_link TEXT,
    firebase_storage_images TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_tourist_locations_taluka ON tourist_locations(taluka);
CREATE INDEX IF NOT EXISTS idx_tourist_locations_place_name ON tourist_locations(place_name);
CREATE INDEX IF NOT EXISTS idx_tourist_locations_active ON tourist_locations(is_active);
CREATE INDEX IF NOT EXISTS idx_tourist_locations_sr_no ON tourist_locations(sr_no);

-- Create or replace the update timestamp function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Add trigger to update updated_at timestamp
CREATE TRIGGER update_tourist_locations_updated_at 
    BEFORE UPDATE ON tourist_locations 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert all data from Excel file
INSERT INTO tourist_locations (
    sr_no, place_name, taluka, location, latitude_longitude,
    video_link, description, famous_for, best_time_to_visit,
    ideal_duration, images_drive_link, firebase_storage_images
) VALUES
(1,
    'Ganpatipule Beach & Ganpati Mandir',
    'Ratnagiri',
    'Ganpatipule, Tal. Ratnagiri, Maharashtra 415615',
    NULL,
    'https://www.youtube.com/shorts/jHyHmWgkijw',
    'A beautiful clean beach with a naturally formed Swayambhu Ganpati idol. Perfect for sunrise/sunset, spiritual atmosphere, and long beach walks.',
    'Temple, beach, photography, coastal route.',
    'Oct–Feb',
    '2–3 hours',
    'https://drive.google.com/drive/folders/1HO6nwAxOkIDRxTEGSYsYkkIkL8hoQ9b8?usp=sharing',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105022.png?alt=media&token=d43b0073-4f02-4677-b9d4-f0473a58ea9b, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105031.png?alt=media&token=8c532feb-a409-432d-9a5f-1f0df70c2325, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105120.png?alt=media&token=fd201e18-4b4c-4de9-9d27-6b013ce3ac73, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105201.png?alt=media&token=6cc3b989-e30c-4bab-a8c7-3b3f1ff006b7, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105352.png?alt=media&token=44291c9c-b2bc-4c7d-b284-e26d743b532c '),
(2,
    'Ratnadurg Fort (Bhagwati Fort)',
    'Ratnagiri',
    'Fort Rd, Mirya, Ratnagiri, Maharashtra 415639',
    NULL,
    'https://www.instagram.com/reel/DQmEPxgjCjW/?utm_',
    'A massive sea-cliff fort offering panoramic Arabian Sea views. Sunset point is excellent. 700+ year history.',
    'Sea views, lighthouse, photography, fort’s history.',
    'Nov–Feb',
    '1.5–2 hours',
    'https://drive.google.com/drive/folders/1HDDZ87N19ZkNuPKVGpedjgc_h-6WE5Gm?usp=drive_link',
    ' https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105502.png?alt=media&token=bcbd1294-976b-4fae-ae45-e9ef7ca8d29c, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105518.png?alt=media&token=378e5ad2-945b-4ea5-b8c5-a7563cba12da, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105543.png?alt=media&token=779eabf7-9a96-4a4b-a515-3b64520681ed, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105617.png?alt=media&token=65eb9979-0b66-46b8-a344-f5f83d3ef016, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105856.png?alt=media&token=5272ee21-addf-48bc-adab-6868a5bdfbab'),
(3,
    'Thiba Palace',
    'Ratnagiri',
    'Thiba Palace Rd, Ratnagiri city, Maharashtra 415612',
    NULL,
    'https://www.youtube.com/shorts/17kB7lu7Xkk',
    'Historical palace where the King of Burma (Myanmar) was kept in exile. Architecture + gardens worth seeing.',
    'Burmese king’s story, heritage building.',
    'Throughout the year',
    '1 hour',
    'https://drive.google.com/drive/folders/1hP8BPpQiXpK4MvOpvmvhW7DSrF2lkJwN?usp=drive_link',
    ' https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F3-Thiba%20Palace%2FScreenshot%202025-12-15%20105731.png?alt=media&token=5bc2b43f-4bf3-45d3-bf1b-6a5f477ddb04, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F3-Thiba%20Palace%2FScreenshot%202025-12-15%20110100.png?alt=media&token=d6ec672d-3bcc-4638-afb4-c4af9fc6db2d, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F3-Thiba%20Palace%2FScreenshot%202025-12-15%20110116.png?alt=media&token=24b376ce-d160-4de8-a510-9ae70829e30c, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F3-Thiba%20Palace%2FScreenshot%202025-12-15%20110310.png?alt=media&token=8aa492c1-ead4-4057-ae9d-17c4bbf32c23, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F3-Thiba%20Palace%2FScreenshot%202025-12-15%20110431.png?alt=media&token=9135fb0f-d23f-49be-bdd8-838d170fcf81 '),
(4,
    'Mandavi Beach (Black Sand Beach)',
    'Ratnagiri',
    'Mandavi Beach, near Ratnagiri Jetty, Ratnagiri 415612',
    NULL,
    'https://www.instagram.com/reel/CyN6ov7Ptdu/?utm_',
    'Popular sunset point inside city; black-sand beach; good for families. Clean promenade.',
    'Black sand, sunset, fish market nearby.',
    'Evening',
    '1–1.5 hours',
    'https://drive.google.com/drive/folders/1VrjtvuI04Am_JbnDAJawQlm0buibabbo?usp=drive_link',
    ' https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F4-Mandavi%20Beach%20(Black%20Sand%20Beach)%2FScreenshot%202025-12-15%20110554.png?alt=media&token=9adc038f-5a6e-4e9e-8e22-af654f2cb08c, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F4-Mandavi%20Beach%20(Black%20Sand%20Beach)%2FScreenshot%202025-12-15%20110622.png?alt=media&token=72de0d75-70c1-43cf-892f-660ba28196d2, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F4-Mandavi%20Beach%20(Black%20Sand%20Beach)%2FScreenshot%202025-12-15%20110644.png?alt=media&token=5592f067-a73a-4b20-9afc-df47517fc837, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F4-Mandavi%20Beach%20(Black%20Sand%20Beach)%2FScreenshot%202025-12-15%20110711.png?alt=media&token=7994f284-09d5-47aa-9c0e-aa4bd3e60ab5 '),
(5,
    'Jaigad Fort',
    'Ratnagiri',
    'Jaigad, Dist. Ratnagiri, Maharashtra 415614',
    NULL,
    'https://www.instagram.com/reel/DOV2ozljBfx/?utm_',
    'A large 16th-century coastal fort with deep moats, thick walls, and fantastic sea views. Windy cliffs.',
    'History, bastions, ocean ridge.',
    'Oct–March',
    '2 hours',
    'https://drive.google.com/drive/folders/1q8WTExjQGSVSRz6Cv0JF6fl431t7Go1U?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20111915.png?alt=media&token=0df488f6-95b9-4247-8e87-7cff1c5456e9, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20111957.png?alt=media&token=49f0517e-5e62-433a-ad43-2ea62f48074d, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20112018.png?alt=media&token=48d53788-ae60-482d-bc26-2ebafa9f649a, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20112039.png?alt=media&token=51ebb506-cbd9-4cae-be05-9570e819a3cb, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20112207.png?alt=media&token=8feb889a-a7e7-4557-a4c4-22523d0fce5f, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20112246.png?alt=media&token=b6d89970-45b0-43da-8fb7-4878e4705742, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F5-Jaigad%20Fort%2FScreenshot%202025-12-15%20112323.png?alt=media&token=5aa8bc40-b641-4feb-909d-d364e7f986e7 '),
(6,
    'Jaigad Lighthouse',
    'Ratnagiri',
    'Jaigad Lighthouse Rd, Jaigad, Maharashtra 415614',
    NULL,
    'https://www.instagram.com/reel/C-fZnZKtvWs/?utm_',
    'Lighthouse on a cliff near Jaigad Fort. Offers a 360° Konkan coastline view.',
    'Height, views, photography.',
    'Morning',
    '30 min',
    'https://drive.google.com/drive/folders/131IUhA5hqx3o_jKj0xRNazFTlneHMKmK?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F6-Jaigad%20Lighthouse%2FScreenshot%202025-12-15%20112440.png?alt=media&token=81e0e41e-5687-44ef-9b86-921a6b5f78c6, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F6-Jaigad%20Lighthouse%2FScreenshot%202025-12-15%20112501.png?alt=media&token=ccf17c56-9904-4505-a2bd-f7595b92cc52, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F6-Jaigad%20Lighthouse%2FScreenshot%202025-12-15%20112526.png?alt=media&token=92e7d09d-1728-4bf9-9da5-03e48af178da, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F6-Jaigad%20Lighthouse%2FScreenshot%202025-12-15%20112540.png?alt=media&token=ce10e66e-5928-44ab-93a2-c47bc104ebd4 '),
(7,
    'Aare Ware Beach (Twin Beaches)',
    'Ratnagiri',
    'Aare–Ware Rd, Ganpatipule – Ratnagiri coastal route',
    NULL,
    'https://www.instagram.com/reel/DPgejhaiFik/?utm_',
    'Two untouched, natural beaches connected by a cliff road. Scenic drive.',
    'Scenic drive, drone shots, blue sea.',
    'Anytime',
    '45 min – 1 hour',
    'https://drive.google.com/drive/folders/17y1hZKZt3vQK8q2DXTZz5EXyCON36fKB?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F7-Aare%20Ware%20Beach%20(Twin%20Beaches)%2FScreenshot%202025-12-15%20112709.png?alt=media&token=38ab4893-0d7e-4456-8a9d-cc8b29026078, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F7-Aare%20Ware%20Beach%20(Twin%20Beaches)%2FScreenshot%202025-12-15%20112737.png?alt=media&token=72fe726e-54f5-444a-bef5-0c1b6f3e8d92, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F7-Aare%20Ware%20Beach%20(Twin%20Beaches)%2FScreenshot%202025-12-15%20112800.png?alt=media&token=f4aeaa7c-391a-4ead-98b1-ac3a4aac47a9, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F7-Aare%20Ware%20Beach%20(Twin%20Beaches)%2FScreenshot%202025-12-15%20112857.png?alt=media&token=a635639d-eb9b-49d4-97fe-26bcfc03bd50 '),
(8,
    'Kasheli Beach',
    'Ratnagiri',
    'Kasheli Village, Near Purnagad Fort, Ratnagiri',
    NULL,
    'https://youtu.be/KCive5LXExw?si=sDeWYDC4AJMkynVr',
    'A scenic beach known for its peaceful environment and fishing village culture. Wide sandy patches & stunning sunsets.',
    'Excellent for cultural vlogs',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1qF6oqaxkwuXcxaAS_or7OuxGgu71jASt?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F8-Kasheli%20Beach%2FScreenshot%202025-12-15%20113157.png?alt=media&token=ad7561d2-52f7-4663-84d3-930c793cd892, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F8-Kasheli%20Beach%2FScreenshot%202025-12-15%20113217.png?alt=media&token=bdb45abe-1ccc-434a-bf49-1debbc37774c, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F8-Kasheli%20Beach%2FScreenshot%202025-12-15%20113246.png?alt=media&token=541becfe-f19c-4c15-9ead-7eda7cbd8666, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F8-Kasheli%20Beach%2FScreenshot%202025-12-15%20113301.png?alt=media&token=da453ace-486e-4397-b44a-9fd11ba3dec1 '),
(9,
    'Marine Museum (Aquarium)',
    'Ratnagiri',
    'Near Mandavi Beach, Ratnagiri City',
    NULL,
    'https://youtu.be/KWBzl8hb6qI?si=8khb7Da6KllCklCL',
    'Small marine museum displaying fish species, shells, preserved sea life — great for kids.',
    'Fish species, marine education.',
    'Any',
    '20–30 min',
    'https://drive.google.com/drive/folders/1Ld2Apzm6gFhbwZHWKnhELjh7liiv_Yhc?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F9-Marine%20Museum%20(Aquarium)%2FScreenshot%202025-12-15%20113425.png?alt=media&token=cbb2a249-00a2-4303-bd82-8599670ddcea, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F9-Marine%20Museum%20(Aquarium)%2FScreenshot%202025-12-15%20114046.png?alt=media&token=5ece0a21-956b-4632-9cdc-2de82e2ba9c2 '),
(10,
    'Bhatye Beach',
    'Ratnagiri',
    'Bhatye Village, Ratnagiri 415612',
    NULL,
    'https://www.instagram.com/reel/DM7W0ypBnnI/?utm_',
    'Long straight beach with shallow waters, perfect for walking, chilling, and photography. Less crowd, windy and peaceful.',
    'Calm beach, seafood near by, bridge view.',
    'Sunset',
    '1–1.5 hrs',
    'https://drive.google.com/drive/folders/14x1GozESTjpVotwWiGF9N20kdrCT0pY7?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F10-Bhatye%20Beach%2FScreenshot%202025-12-15%20114136.png?alt=media&token=80857a3c-27e0-48ba-b08a-26686fa15c1c, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F10-Bhatye%20Beach%2FScreenshot%202025-12-15%20114150.png?alt=media&token=3aa8a89e-b233-4779-802b-38b1c0d1d4c8, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F10-Bhatye%20Beach%2FScreenshot%202025-12-15%20114204.png?alt=media&token=6961501d-cb32-4653-85fb-f2b3b53fe377 '),
(11,
    'Arey-Ware Ghat Scenic Road',
    'Ratnagiri',
    'Ratnagiri–Ganpatipule Coastal Highway',
    NULL,
    'https://youtube.com/shorts/SrFVysEBWpE?si=dTtwr-5uZt6er0qI',
    'One of Maharashtra’s best coastal roads — turquoise ocean, cliffs, hills, greenery.',
    'Road trip, cinematic drone shots.',
    'Evening',
    '30 min (drive)',
    'https://drive.google.com/drive/folders/1ELxlUZbZYcP5AlzvQsJN4NkolNAU6Jtu?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F11-Arey-Ware%20Ghat%20Scenic%20Road%2FScreenshot%202025-12-15%20114429.png?alt=media&token=53a2cbdd-91aa-4285-ae0e-6c7150ff677e, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F11-Arey-Ware%20Ghat%20Scenic%20Road%2FScreenshot%202025-12-15%20114445.png?alt=media&token=8c6240ed-e95e-4654-b620-da0feb52499f, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F11-Arey-Ware%20Ghat%20Scenic%20Road%2FScreenshot%202025-12-15%20114514.png?alt=media&token=e099c566-ef7f-4071-82d4-12187d489ec1'),
(12,
    'Purnagad Fort',
    'Ratnagiri',
    'Purnagad Village, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DRE9xSODJQw/?utm_',
    'Stunning sea-facing fort associated with Kanhoji Angre. Peaceful, untouched fort.',
    'Sea fort view + history.',
    'Winter',
    '1–1.5 hrs',
    'https://drive.google.com/drive/folders/1eIy4FdT9vBzSikrsHvllG66vZgi5VdmX?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F12-Purnagad%20Fort%2FScreenshot%202025-12-15%20115857.png?alt=media&token=576179b0-b379-4f7a-9eba-8e79a0eb3aa8, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F12-Purnagad%20Fort%2FScreenshot%202025-12-15%20115918.png?alt=media&token=06db8bf8-360f-45ed-8cfc-00d806c138f1, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F12-Purnagad%20Fort%2FScreenshot%202025-12-15%20115940.png?alt=media&token=ebfbf549-f912-4e0d-acd7-82483a71e7e4'),
(13,
    'Malgund Village – Birthplace of Keshavsut',
    'Ratnagiri',
    'Malgund Village, Near Ganpatipule, Ratnagiri',
    NULL,
    'https://www.youtube.com/shorts/ux40ZeXpGPU',
    'A cultural and literary village with a museum dedicated to Marathi poet Kavi Keshavsut.',
    'Good for literature lovers. Peaceful village ambiance.',
    'Anytime',
    NULL,
    'https://drive.google.com/drive/folders/1j_Fq7mm4bVDXdJ4aAuL-FUtrVjdSzZF5?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F13-Malgund%20Village%20–%20Birthplace%20of%20Keshavsut%2FScreenshot%202025-12-15%20120139.png?alt=media&token=8ce46fa4-6786-4f87-8d37-9cf535c7613e,
https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F13-Malgund%20Village%20–%20Birthplace%20of%20Keshavsut%2FScreenshot%202025-12-15%20120158.png?alt=media&token=0bac628d-11a3-4e50-baf2-624f31a1c675,
https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F13-Malgund%20Village%20–%20Birthplace%20of%20Keshavsut%2FScreenshot%202025-12-15%20120224.png?alt=media&token=f7d09ebe-0500-4e66-b13a-1ddc5fb5d092'),
(14,
    'Kalbadevi Temple & Beach',
    'Ratnagiri',
    'Kalbadevi, Ratnagiri District,',
    NULL,
    'https://www.instagram.com/reel/DJBvasZRzNL/?utm_',
    'An old temple dedicated to Goddess Kalbadevi, located beside a serene beach. The combination of spirituality and scenic beauty makes it a must-visit.',
    'Peaceful atmosphere.
 Perfect for family visits.
 Good for religious functions.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1j9TWBjXKh3cCn6vke4fzyvWiuYAhtjyT?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F14-Kalbadevi%20Temple%20%26%20Beach%2FScreenshot%202025-12-15%20120449.png?alt=media&token=cafa8d58-ddef-4896-a94e-930a633b5745, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F14-Kalbadevi%20Temple%20%26%20Beach%2FScreenshot%202025-12-15%20120514.png?alt=media&token=1ad2b95f-eef4-4e46-a17a-b1d6f8c048c9'),
(15,
    'Pokharbav Ganpati Mandir',
    'Ratnagiri',
    'Pokharbav, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DEhmhBdtOuj/?utm_',
    'A sacred ancient Ganpati temple built in traditional Konkani style. Surrounded by greenery and village landscape.',
    'Peaceful religious spot.
 Local festivals celebrated grandly.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/13_ANM68EMaGlqkyxrUG1_-NUisnbh6u2?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F15-Pokharbav%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20202756.png?alt=media&token=db3b2a7a-1bf8-4f43-9fc8-c17d903d8007, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F15-Pokharbav%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20202924.png?alt=media&token=77de1856-9d48-4612-9dcf-558cbdcf26d9 '),
(16,
    'Karhateshwar Temple',
    'Ratnagiri',
    'Near Jaigad Fort, Karhateshwar, Ratnagiri 415614',
    NULL,
    'https://www.instagram.com/reel/DOn4OVsjM0T/?utm_',
    'A historical Shiva temple located on a cliff overlooking the Arabian Sea. One of the most stunning and peaceful coastal temples in the Konkan region.',
    'Sea view is extraordinary.
 Great photography spot.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1fzRd4V_VSFxrr97kmkKiT6J0nNm9Fzo5?usp=drive_link',
    ' https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F16-Karhateshwar%20Temple%2FScreenshot%202025-12-16%20001630.png?alt=media&token=294f620f-b4a9-4e35-9226-6055b9a55beb, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F16-Karhateshwar%20Temple%2FScreenshot%202025-12-16%20001646.png?alt=media&token=f966605e-06f2-4535-b38f-35e6166890da, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F16-Karhateshwar%20Temple%2FScreenshot%202025-12-16%20001750.png?alt=media&token=a86b733a-243f-4e0b-8c04-c987dc2673e8 '),
(17,
    'Panval Waterfall',
    'Ratnagiri',
    'Panval Village, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DMffB9IvxOx/?utm_',
    'A picturesque waterfall hidden deep in the forest. Best enjoyed after heavy monsoon rains. Great spot for nature lovers.',
    'Some trekking required.
 Safe during early monsoon',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1uhu5Yo8oaPFkjJaNiCE3B96f0ULnPdDI?usp=drive_link',
    'https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F18-Mirya%20Beach%2FScreenshot%202025-12-16%20014714.png?alt=media&token=5274af6b-33e2-43c4-8d1d-4eed1d68e642, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F18-Mirya%20Beach%2FScreenshot%202025-12-16%20014724.png?alt=media&token=bfa7b506-fb33-4a6c-867c-2a75d0021cf2, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F18-Mirya%20Beach%2FScreenshot%202025-12-16%20014734.png?alt=media&token=d40f3a74-4e82-4be1-ae16-fe59ce1e5614, https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F18-Mirya%20Beach%2FScreenshot%202025-12-16%20014744.png?alt=media&token=4555e3a4-89a5-4f63-bf5a-0746edbccf0b '),
(18,
    'Mirya Beach',
    'Ratnagiri',
    'Mirya Village, Ratnagiri City, Maharashtra 415612',
    NULL,
    'https://www.instagram.com/reel/DQRd6MAjJLQ/?utm_',
    'Mirya Beach is close to Ratnagiri city and known for its calm backwaters, picturesque fishing boats, and long stretch of walkable shoreline. The beach is less commercial, ideal for families and peaceful evening walks.',
    'Walking, photography, fishing boat watching, sunrise & sunset views.',
    'November – February',
    NULL,
    'https://drive.google.com/drive/folders/1Y0aJ6H8jk528g02H6ltvDSWHJRSx5qwV?usp=drive_link',
    NULL),
(19,
    'Avachitwadi village, Malgund',
    'Ratnagiri',
    NULL,
    NULL,
    'https://www.instagram.com/reel/DQ4AHRLjHRR/?utm_',
    'This peaceful pond surrounded by lush greenery and absolute silence. The water is crystal clear — it almost looks unreal under sunlight.',
    'This is one of those rare places where you can just sit, breathe, and forget time.',
    'Anytime',
    NULL,
    'https://drive.google.com/drive/folders/1uNjq3YfDxPcvFFuComlmuh1uIn3qMwO3?usp=drive_link',
    NULL),
(20,
    'Hanuman Kundi (Waterfall Point)',
    'Ratnagiri',
    'Near Pawas Village, Ratnagiri – Pawas Road, Maharashtra 415616',
    NULL,
    'https://www.youtube.com/watch?v=xRqY5F5jckE&t=52s',
    'Small natural waterfall + rock formation surrounded by dense greenery. Calm hidden spot; good for monsoon nature lovers. Not commercial, peaceful and less crowded.',
    NULL,
    'Monsoon & post-monsoon (July–Oct)',
    NULL,
    'https://drive.google.com/drive/folders/13uBYruKsMnqK3klXq61MIxpZmu85NBAz?usp=drive_link',
    NULL),
(21,
    'Jay Vinayak Temple',
    'Ratnagiri',
    'JSW Township, Kachare Village, Taluka Jaigad, Dist. Ratnagiri, Maharashtra 415614',
    NULL,
    'https://www.instagram.com/reel/DPoaueqDzB6/?utm_',
    'Beautiful, well-maintained modern temple of Lord Ganesha. Temple has pagoda-style roof, attractive gardens & pond, calm ambiance. Good for spiritual visit + peaceful time amidst greenery.',
    'Lovely brass idol of Ganesha, clean gardens, peaceful atmosphere, good stop if you visit nearby coastal forts/beaches.',
    'Morning or evening (sunrise or aarti time) — 6 AM–10 AM, 5 PM–6 PM recommended',
    '30–45 minutes (or more if you include stroll in gardens / photography)',
    'https://drive.google.com/drive/folders/1piPOGy1EkuY-_Gpijzqu9Wvh8fnF_EJe?usp=sharing',
    NULL),
(22,
    'Phansavle Bridge',
    'Ratnagiri',
    'Phansavle, Ratnagiri – near river crossing',
    NULL,
    'https://www.instagram.com/reel/DRWDdnwiGLZ/?utm_',
    'Scenic old bridge with beautiful river views, greenery, and photogenic surroundings — popular among locals.',
    'River views, scenic photography spot',
    'Oct–Feb',
    '15–30 min',
    'https://drive.google.com/drive/folders/1sKMbyfhnUQkVJqui6dE-QDx6o0AfkuBL?usp=drive_link',
    NULL),
(23,
    'Kanakaditya Temple (Sun Temple)',
    'Lanja',
    'Kasheli village, Tal. Lanja, Dist. Ratnagiri',
    NULL,
    'https://www.youtube.com/shorts/EX_T7Mg8oX0',
    'One of the few Sun Temples in India. Very clean, surprisingly peaceful, unique architecture.',
    'Sun God temple, rare structure.',
    'Morning hours',
    '30 min',
    'https://drive.google.com/drive/folders/1wu1YF-zuIknEZV8QAcDbEVIn-JD1lSnG?usp=drive_link',
    NULL),
(24,
    'Devgad Beach + Fort',
    NULL,
    'Devgad, Sindhudurg district border (1.5 hours from Ratnagiri)',
    NULL,
    'https://www.youtube.com/watch?v=o4v0XIjUvGU',
    'Clear blue-water beach + hilltop fort + lighthouse. Famous for Alphonso mangoes.',
    'Clean beach, mango farms.',
    'Winter',
    'Half-day',
    'https://drive.google.com/drive/folders/1khJB8okdRmGpqpgHnpXNsDhozb9UEHH1?usp=drive_link',
    NULL),
(25,
    'Kunkeshwar Temple & Beach',
    NULL,
    'Kunkeshwar, Devgad Road, near Ratnagiri border',
    NULL,
    'https://youtu.be/Y1mbBxaJRYg?si=UkyQa0wcjo25FTvB',
    'A beautiful Shiva temple right at the edge of the Arabian Sea. The beach is clean and less commercial.',
    'Sea-facing temple, clean beach.',
    'Early morning',
    '1 hour',
    'https://drive.google.com/drive/folders/1Ab1M_aQlgU3XxJJ7cv01_QTrZtHX-R6k?usp=drive_link',
    NULL),
(26,
    'Velas Beach (Turtle Festival)',
    NULL,
    'Velas Village, Ratnagiri 415208',
    NULL,
    'https://www.youtube.com/shorts/qUCZM22IpIw',
    'Conservation site for Olive Ridley turtles. Every year hatchlings are released into the sea.',
    'Turtle hatching festival.',
    'Feb–April',
    'Half day',
    'https://drive.google.com/drive/folders/1NuUm2rjVXuKJpYyiQXK_aqc_LH22pv2T?usp=drive_link',
    NULL),
(27,
    'Anjarle Beach & Kadyavarcha Ganpati',
    'Dapoli',
    'Anjarle, Dapoli (Ratnagiri district)',
    NULL,
    'https://www.instagram.com/reel/DHgG77fglWD/?utm_',
    'Stunning beach + hilltop Ganpati temple with a panoramic view. Less commercial, very scenic.',
    'Clear beach, hilltop temple, photography.',
    'Winter',
    '2 hrs',
    'https://drive.google.com/drive/folders/1UabUrUPj__DFmGOZ_1uBezp9lMiVEtli?usp=drive_link',
    NULL),
(28,
    'Murud Beach',
    'Dapoli',
    'Murud, Dapoli, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DFWxlJQNkKl/?utm_source=ig_web_button_share_sheet',
    'One of Dapoli’s most visited beaches; water sports, horse rides, and long stretches.',
    'Watersports, dolphin-spotting nearby.',
    'Nov–Feb',
    '2–3 hrs',
    'https://drive.google.com/drive/folders/1xof6LIK-hjHq2bsF3fQyiPXWGagCPuCc?usp=drive_link',
    NULL),
(29,
    'Harnai Port & Fish Auction Market',
    'Dapoli',
    'Harnai, Dapoli, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DPbPRf-ka9_/?utm_',
    'Live fish auction market — huge boats, fresh catch, real Konkan culture.',
    'Fish auction, local seafood culture.',
    NULL,
    '1 hr',
    'https://drive.google.com/drive/folders/12iLRLCaOBWm-GGFZDz-EfAA9teB8uuO4?usp=drive_link',
    NULL),
(30,
    'Suvarnadurg Fort (Sea Fort)',
    'Dapoli',
    'Off Harnai coast, Dapoli, accessible by boat',
    NULL,
    'https://www.instagram.com/reel/DIoNHZAA41X/?utm_',
    'Historic sea fort of Shivaji Maharaj, accessible via boat ride; adventurous and scenic.',
    'Sea fort adventure, history.',
    'Winter',
    '2 hrs',
    'https://drive.google.com/drive/folders/1NTZnCI1RcIPUMGfh_1nePyCWraymLxFq?usp=drive_link',
    NULL),
(31,
    'Panhalekaji Caves',
    'Dapoli',
    'Near Dapoli, Ratnagiri district',
    NULL,
    'https://www.instagram.com/reel/CpFoH_kjfYG/?utm_',
    'Ancient Buddhist–Hindu caves with carvings; located near a river. Hidden, underrated place.',
    'Cave carvings, archaeology.',
    'Winter',
    '1–1.5 hrs',
    'https://drive.google.com/drive/folders/19ziZV0adlaUYZzwxrTMbXrpXoda8TepF?usp=drive_link',
    NULL),
(32,
    'Ladghar Beach',
    'Dapoli',
    'Ladghar, Dapoli, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DIWLp0FNsZ-/?utm_',
    'Known as “Red Sea” due to reddish sand tint. Water sports, boat rides, dolphin sighting.',
    'Red sand shade, watersports, dolphins.',
    'Winter',
    '1.5–2 hrs',
    'https://drive.google.com/drive/folders/19Z1yAoQvSJXGm7a2rfz2JFrG7Bdrw8dd?usp=drive_link',
    NULL),
(33,
    'Kolthare Beach',
    'Dapoli',
    'Kolthare Village, Dapoli, Ratnagiri',
    NULL,
    'https://www.youtube.com/watch?v=FCzr7grXM4Y',
    'Extremely clean, untouched beach. No crowd. Perfect for peaceful travellers.',
    'Virgin beach, clean coastline.',
    'Oct–Feb',
    '1–1.5 hrs',
    'https://drive.google.com/drive/folders/1cxu9AsI9mxBGrdiX_WbdTj_UPmmpXH48?usp=drive_link',
    NULL),
(34,
    'Karde Beach',
    'Dapoli',
    'Karde Village, Dapoli, Ratnagiri',
    NULL,
    'https://www.youtube.com/watch?v=pbA0QGlW4Lw',
    'Long clean beach, popular for dolphin rides. Several homestays nearby.',
    'Dolphin safari.',
    'Morning',
    '1–2 hrs',
    'https://drive.google.com/drive/folders/1-Ib4-mh4CzzdY16o99hUoVshjO9-mv2W?usp=drive_link',
    NULL),
(35,
    'Dabhol Port & Chandika Devi Cave Temple',
    'Dapoli',
    'Dabhol, Dapoli, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DO3lyHwDLVx/?igsh=',
    'Port area + Goddess Chandika Devi’s underground cave temple. Ancient & mystical ambience.',
    'Natural cave temple, ancient idol.',
    'Morning',
    '45 min',
    'https://drive.google.com/drive/folders/16DSTxhxphyn9YL_np71oRPnimKQlF6Rb?usp=drive_link',
    NULL),
(36,
    'Keshavraj Temple',
    'Dapoli',
    'Asud, Dapoli, Ratnagiri, Maharashtra 415713',
    NULL,
    'https://www.instagram.com/reel/DH8bm1Pttbz/?utm_',
    'A peaceful temple situated inside a dense forest with a freshwater stream flowing alongside the stone steps. The path to the temple is scenic with lush greenery, making it one of the most serene spiritual spots in Ratnagiri.',
    'Ideal for nature lovers and a calm getaway.',
    'Early morning or winter season',
    NULL,
    'https://drive.google.com/drive/folders/1Qj343zATN7efTSNtqzk9TtwqDebNTg12?usp=drive_link',
    NULL),
(37,
    'Kanakdurg Fort',
    'Dapoli',
    'Harne Port, Dapoli, Ratnagiri',
    NULL,
    'https://www.youtube.com/watch?v=qsZq0azfr9I&t=124s',
    'Sea-side fort built on rocks; offers stunning sea waves, port views & peaceful historic ambiance.',
    'Adjacent to Suvarnadurg; sea-wave photography',
    NULL,
    '45 mins – 1 hour',
    'https://drive.google.com/drive/folders/1z8aKa7U2mycUBmJAnMIwYPDMZI0bgSGc?usp=drive_link',
    NULL),
(38,
    'Fattegad Fort',
    'Dapoli',
    'Harne, Near Murud–Dapoli Road, Ratnagiri',
    NULL,
    'https://www.youtube.com/watch?v=qsZq0azfr9I&t=124s',
    'Small fort near fishing harbor with old gateways & bastions; good for quick visit & marine views.',
    'Historic defense fort, fishermen activities',
    'Nov–Feb',
    '30–45 mins',
    'https://drive.google.com/drive/folders/1emeq85hQFXviTmmx0cmLWzUzsMwTk_ap?usp=sharing',
    NULL),
(39,
    'Goa Fort (Gabriel Fort)',
    'Dapoli',
    'Anjarle – Harnai Coastline, Dapoli',
    NULL,
    'https://www.youtube.com/watch?v=DCoEyVk4M5k',
    'Calm old coastal fort with cliffs, sea breeze & scenic ocean landscapes; peaceful & less crowd',
    'Quiet fort with panoramic coastline',
    'Oct–Feb',
    '1 hour',
    'https://drive.google.com/drive/folders/18sV_kxPjwzDX6GWxBtdwX2hErivXoQkk?usp=drive_link',
    NULL),
(40,
    'Kelshi',
    'Dapoli',
    'Kelshi Village, Dapoli Taluka, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DJwfJoLM3Rd/?utm_',
    'Quiet, clean, long beach with soft sand, surrounded by dunes and coconut trees. Known for Yakub Baba Dargah, Mahalaxmi Temple, and beautiful sunsets. One of the most peaceful beaches in Dapoli region.',
    'Clean beaches, dunes, temples, village walks, peaceful offbeat location',
    'Oct–March',
    '2–3 hours (half day if exploring village)',
    'https://drive.google.com/drive/folders/1UgPeF4WYfnljRM9hugmouaGF4CVVPAQA?usp=drive_link',
    NULL),
(41,
    'Guhagar Beach',
    'Guhagar',
    'Guhagar town, Ratnagiri District',
    NULL,
    'https://www.youtube.com/shorts/Q1p4NxiJpAI',
    'Clean, broad, untouched beach with coconut trees & quiet vibes. Popular with families.',
    'Clean sandy beach.',
    'Oct–Feb',
    '2 hrs',
    'https://drive.google.com/drive/folders/1q4TqkqSk20vfeW6SIyVTM8H85NZYOHpj?usp=drive_link',
    NULL),
(42,
    'Hedvi Dashabhuja Ganpati & Hedvi Beach',
    'Guhagar',
    'Hedvi, Guhagar, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DDuO4_2vz2u/?utm_',
    'Unique 10-handed Ganpati idol + serene beach + natural rock gorge (Baman Ghal).',
    '10-hand idol, natural gorge.',
    'Morning',
    '1 hr',
    'https://drive.google.com/drive/folders/18oczlfhWqOgE2fFxieIrlbKnU50dkOB5?usp=drive_link',
    NULL),
(43,
    'Marleshwar Waterfall & Cave Temple',
    NULL,
    'Chiplun – Marleshwar Road, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DM7uyZoN8ZP/?utm_',
    'Cave temple in Sahyadri + huge waterfall (especially powerful in monsoon).',
    'Waterfall, Shiva cave, trekking trail.',
    'Half-day',
    'Half-day',
    'https://drive.google.com/drive/folders/151l5ahBWqgPnWJ3IRFq3ShRSc4yTc-gh?usp=drive_link',
    NULL),
(44,
    'Tilak Gram (Birthplace of Lokmanya Tilak – near Ratnagiri)',
    NULL,
    'Chikhali village, Ratnagiri',
    NULL,
    'https://www.youtube.com/shorts/mRPutYvJ1Yk',
    'Area dedicated to Lokmanya Bal Gangadhar Tilak’s legacy; simple, peaceful, historical.',
    'Historical importance.',
    'Any',
    '30 min',
    'https://drive.google.com/drive/folders/1PFAVfVGNGcgxOjTndUnuFKNQSVCzwFAa?usp=drive_link',
    NULL),
(45,
    'Gopalgad Fort (Anjanvel Fort)',
    'Guhagar',
    'Anjanwel Village, Guhagar–Dabhol Road, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DIS2xFgicEI/?utm_',
    'Sea-facing fort with huge walls, cliff edges, and greenery. Great panoramic views.',
    'Sea-view fort, scenic cliff top.',
    'Nov–Feb',
    '1 hr',
    'https://drive.google.com/drive/folders/1rdNWzgvRAihaNiJWQUTTmdYU2uEMv_nC?usp=drive_link',
    NULL),
(46,
    'Baman Ghal (Natural Gorge at Hedvi)',
    'Guhagar',
    'Hedvi, near Dashabhuja Temple, Guhagar',
    NULL,
    'https://www.youtube.com/shorts/i9pb-6tzuxY',
    'Narrow rock gorge where waves shoot up like a fountain during high tide.',
    'Natural gorge + water jet.',
    'High tide',
    '20–30 min',
    'https://drive.google.com/drive/folders/1ZtH7gm-wc-sy3HFnp0-Xq9Wxqq3h2lYV?usp=drive_link',
    NULL),
(47,
    'Palshet Beach (Unexplored)',
    'Guhagar',
    'Palshet Village, Guhagar Taluka, Ratnagiri 415703',
    NULL,
    'https://youtu.be/jUhqfYMu3a8?si=ceTTJS6LZJ_u8VfI',
    'A quiet beach with natural rock formations, minimal crowd, and clean water—ideal for peaceful visits.',
    'Great sunset spot',
    'Anytime',
    NULL,
    'https://drive.google.com/drive/folders/1GZoWb9JD2iiFv8rT9BT3zxjY7qvbPUu-?usp=drive_link',
    NULL),
(48,
    'Velneshwar Beach',
    'Guhagar',
    'Velneshwar village, Guhagar taluka, Ratnagiri district, Maharashtra 41572',
    NULL,
    'https://www.youtube.com/watch?v=wn58QnwtuAw',
    'A calm, rock-free sandy beach with clean water, lined with coconut trees — ideal for relaxing, swimming, and long walks. Close to old Shiva temple which gives it spiritual & cultural charm.',
    'Peaceful beach-vibe, safe for swimming, temple + coastal village feel, less crowded compared to main tourist beaches',
    'Oct – Feb (or dry season) for pleasant weather; also good for calm sea & swimming.',
    NULL,
    'https://drive.google.com/drive/folders/18WP7FrQc-1_PfvRmz54fGhxqmkYankmN?usp=drive_link',
    NULL),
(49,
    'Sapteshwar temple',
    'Sangameshwar',
    'Sangameshwar Taluka, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DRjHrElCDQz/?utm_',
    'Ancient Shiva temple where two rivers meet. Surrounded by greenery.',
    'River confluence, old temple.',
    'Monsoon',
    '30–45 min',
    'https://drive.google.com/drive/folders/1bsFf-ZAznDF0nkTzN6yRip5xGQ5V-vSa?usp=drive_link',
    NULL),
(50,
    'Sangameshwar Kasba Area',
    'Sangameshwar',
    'Sangameshwar (Kasba), Sangameshwar Taluka, Ratnagiri District, Maharashtra — at the confluence of Sonavi & Shastri rivers; PIN ~415611',
    NULL,
    'https://www.instagram.com/reel/DC8XWJwITCa/?utm_',
    'Historic kasba built around several old Hemadpanti temples; sit-down market/townfeel at the river confluence — good for a short cultural stop, local temples (Karneshwar), and seeing inland Konkan life.',
    'River-confluence temples, Hemadpanti architecture, local markets, good en-route stop when driving interior Konkan',
    'Oct–Feb (pleasant weather)',
    '30–90 minutes (walk & temple visits)',
    'https://drive.google.com/drive/folders/1umv_Fxo5CEqc6gOxUDwCdNapB9K8cPrW?usp=drive_link',
    NULL),
(51,
    'Tikaleshwar Temple',
    'Sangameshwar',
    'Talavade village (near Devrukh), Sangameshwar Taluka, Ratnagiri District — hilltop temple reached by ~200 steps; nearest town Devrukh',
    NULL,
    'https://www.instagram.com/reel/DLsJP0Hvrda/?utm_',
    'Small hill-top Shiva temple (Tikaleshwar) above Talavade; short trek / stair-climb to a compact shrine with local devotees — popular during Maha Shivratri and for a quick hilltop view.',
    'Hilltop Shiva temple, short trek (200 steps), local pilgrimage spot; good detour if exploring Marleshwar / Sangameshwar route.',
    '30–45 minutes (including climb)',
    NULL,
    'https://drive.google.com/drive/folders/1s76HraORAQ7Yu7PBDkXv1dsFkNNOz7j2?usp=drive_link',
    NULL),
(52,
    'Konkan Railway Scenic Viewpoints (Ratnagiri Belt)',
    'Ratnagiri',
    'Ratnagiri–Nivsar–Aadavali region',
    NULL,
    'https://www.youtube.com/shorts/0UuyKtl_mR4',
    'Iconic rail route with tunnels, bridges, Western Ghats valleys — perfect for drone/videos.',
    'Most scenic railway route.',
    'Monsoon',
    'Travel time',
    'https://drive.google.com/drive/folders/17HFfTSMnMheQ_GD5eMFn7B-gXauP86-P?usp=drive_link',
    NULL),
(53,
    'Ambolgad Fort',
    'Rajapur',
    'Ambolgad, Rajapur, Ratnagiri, Maharashtra 416702',
    NULL,
    'https://www.youtube.com/watch?v=iMYhCpSjips',
    'A lesser-known coastal fort with stunning cliffs facing the Arabian Sea. The fort gives panoramic views of the coastline, fishing villages, and untouched nature. Perfect spot for trekking and photography.',
    'Less crowded, raw natural beauty.
 Good for drone photography',
    'Anytime',
    NULL,
    'https://drive.google.com/drive/folders/1m1NqFDMXcVBFHVB9gWJLrhbJXoMMQUck?usp=drive_link',
    NULL),
(54,
    'Gavkhadi Beach',
    'Rajapur',
    'Gavkhadi, Rajapur Taluka, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/C7QZnKzoE3Q/?utm_',
    'A peaceful, untouched beach surrounded by greenery and small village settlements. Clear water, soft sand, and zero commercial activity make it an ideal calm escape from city noise. Perfect for quiet sunsets.',
    'Photography, calm walks, local seafood',
    'Oct–Feb',
    NULL,
    'https://drive.google.com/drive/folders/1JI7Zy6z2TrGhl2bG_oPfduy0XgJs2hm_?usp=drive_link',
    NULL),
(55,
    'Khorninko Dam',
    'Rajapur',
    'Near Tulsani Village, Rajapur Taluka, Ratnagiri District',
    NULL,
    'https://www.youtube.com/shorts/7cyvybL7IbI',
    'Khorninko Dam is a peaceful offbeat reservoir surrounded by lush greenery and hills. Ideal for nature lovers, it offers serene views, calm water, and the perfect ambience for a quiet outing or photography. The area is less crowded, giving a raw village-side experience.',
    'Good for drone shots & landscape photography',
    'Best for morning/evening visits',
    NULL,
    'https://drive.google.com/drive/folders/1-1Xg4cD7Ob4sSMnrIee_hGJd2XGwnCWP?usp=drive_link',
    NULL),
(56,
    'Wayangani Beach',
    NULL,
    'Wayangani, Near Devgad–Ratnagiri Road – 416612',
    NULL,
    'https://www.youtube.com/watch?v=NxlW0heF9No',
    'A pristine beach located between Ratnagiri and Devgad. Known for turquoise water, clean sand, very low crowd, and natural rock formations.',
    'Good for peaceful stays & homestays',
    'Winter',
    NULL,
    'https://drive.google.com/drive/folders/1a1zMzVhDTLRPd0EgmJ4LStXVbPu2e4yq?usp=drive_link',
    NULL),
(57,
    'Talashi Beach',
    'Rajapur',
    'Talashi Village, Near Rajapur, Ratnagiri District, Maharashtra – 416702',
    NULL,
    'https://www.youtube.com/shorts/aUgUvzHsL-o',
    'A small, silent beach ideal for family visits and peaceful solo trips.',
    'Clean waters and lush surroundings make it perfect for aesthetic reels and shorts.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/14QO8Nv01hUDG0Dp7I4NO9IVbQIX6iD3S?usp=drive_link',
    NULL),
(58,
    'Ambolgad Beach',
    'Rajapur',
    'Ambolgad, Rajapur, Ratnagiri, Maharashtra 416702',
    NULL,
    'https://www.instagram.com/reel/DRZsY6ijAAs/?utm_',
    'A lesser-known coastal fort with stunning cliffs facing the Arabian Sea.',
    'Less crowded, raw natural beauty.',
    'Anytime',
    NULL,
    'https://drive.google.com/drive/folders/1cj2jhuYf8jLGBEgpR1yx9jD3p8Zk4k52?usp=drive_link',
    NULL),
(59,
    'Loteshwar temple',
    'Khed',
    'Near Lote MIDC area, Khed Taluka, Ratnagiri District, Maharashtra 415722',
    NULL,
    'https://www.instagram.com/reel/DRKHdV9jLfC/?utm_',
    'Ancient Shiva temple known for its peaceful surroundings, simple stone architecture, and serene natural setting. A calm spiritual spot away from the crowds.',
    'Small temple, quiet atmosphere, good for devotees & short visits.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1JVtRKky4cTlL4v2UcByqK6ZtLiC2Hobe?usp=drive_link',
    NULL),
(60,
    'Devacha Dongar',
    'Mandangad',
    'Near Mandangad – Dapoli region, Ratnagiri district, Maharashtra',
    NULL,
    'https://www.youtube.com/shorts/n2N_6XFHLks',
    'Devacha Dongar is a stunning hill point in Dapoli, rising about 3,500 meters above sea level. It connects four talukas — Dapoli, Khed, Mahad, and Mandangad — and lies on the border of two districts. The mountain has four settlements mostly inhabited by the Dhangar community. At the centre stands a naturally formed Shankar (Shiva) shrine, which gives the place its name.',
    'The temple is simple, but the surrounding panoramic views are breathtaking. During winter, the cold climate and misty scenery make the experience even more special.',
    'Winter',
    NULL,
    'https://drive.google.com/drive/folders/1eR70l7L0fmadzR73vRgRe3K7i50p7JXT?usp=drive_link',
    NULL),
(61,
    'Mandangad Fort',
    'Mandangad',
    'Mandangad Taluka, Ratnagiri District, Maharashtra 415203',
    NULL,
    'https://www.youtube.com/watch?v=Hui7Alj2EnM',
    'Hill-fort known for its large cannon, ancient bastions, and wide hilltop views. A short trek to reach, surrounded by greenery. Great for beginners.',
    'Ancient fort, trekking point, panoramic views, historic ruins',
    'Nov–Feb',
    '1.5–2 hours',
    'https://drive.google.com/drive/folders/1sw27W_quSAmuWuPu4Q-ieJiWMh2hIIuD?usp=drive_link',
    NULL),
(62,
    'Bankot Fort (Himmatgad)',
    'Mandangad',
    'Bankot village, near Velas – Harihareshwar coastal belt, Ratnagiri district, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/Ce6WZoyIVmv/?utm_',
    'A coastal fort offering sea views, peaceful surroundings, and an old gateway structure. Historically important as a Maratha & Portuguese post.',
    'Sea-fort, photography spot, quiet coastal nature',
    'Oct–Feb',
    '1–1.5 hours',
    'https://drive.google.com/drive/folders/1GcGC6HxJz1p4bxBK3zE4r6rThwKgVPKd?usp=drive_link',
    NULL),
(63,
    'Parshuram Temple (Chiplun)',
    'Chiplun',
    'Parshuram, near Chiplun, Ratnagiri',
    NULL,
    'https://www.youtube.com/shorts/ZImCW5GErSw',
    'Traditional wooden temple dedicated to Bhagwan Parshuram; serene and scenic backdrop.',
    'Wooden architecture, religious importance.',
    'Morning',
    '45 min',
    'https://drive.google.com/drive/folders/1bSU4qJyqNP9MJI-sQERUINsqt6UZPHX4?usp=drive_link',
    NULL),
(64,
    'Ambadwe (Ambedkar’s ancestral village & Memorial)',
    'Mandangad',
    'Ambadwe village, approx 13 km from Mandangad, Ratnagiri-Konkan region, Maharashtra',
    NULL,
    'https://www.youtube.com/watch?v=_f-XlI38izY',
    'Village heritage site — birthplace/village of Dr. Babasaheb Ambedkar’s ancestors. The original house is now a memorial / national-monument under development. Good for history, social-heritage, quiet village-atmosphere.',
    'Historical / Heritage / Social importance; off-beat spot away from beaches/forts',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1F0BdULSaLlOcvokuLljMDBhEJLfbvog3?usp=drive_link',
    NULL),
(65,
    'Shri Ram Mandir Pajpandhari',
    'Dapoli',
    NULL,
    'https://www.instagram.com/reel/DQolcBdgZMz/?utm_',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/13azBidWYiNTDHR57hwkSgDJ-uRv3xZ47?usp=drive_link',
    NULL),
(66,
    'Panhale Durg Fort',
    'Dapoli',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/189j68DYhSmvDicXpAq7TzJI8AY27JKHf?usp=drive_link',
    NULL),
(67,
    'Palgad',
    'Dapoli',
    'Near Dapoli, Ratnagiri district, Konkan region, Maharashtra',
    NULL,
    'https://www.youtube.com/watch?v=958a8lF-MVg',
    'Old fort ruins/hill-fort site offering countryside / forest / hill-fort experience. Good for trekking, exploring lesser-visited heritage locations away from crowds.',
    'Offbeat heritage/fort, trekking, natural surroundings, less commercial — good for travellers seeking quiet, less-touristed forts',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1X_x-nHZymW1EE7Dq6Qv9fQTAfZ8Vaeb1?usp=drive_link',
    NULL),
(68,
    'Unhavare Hot Water Springs',
    'Dapoli',
    'Unhavare Village, Near Dapoli, Ratnagiri District, Maharashtra 415712',
    NULL,
    'https://www.youtube.com/shorts/oxPQo61LuBc',
    'Natural sulphur hot springs located in a peaceful valley surrounded by greenery. Water remains warm throughout the year. Believed to have skin-healing and medicinal properties. Calm, rural atmosphere — perfect for relaxing and nature experience.',
    'Natural hot water springs, sulphur-rich medicinal water, village/rural Konkan experience',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1hluAhc0MA2EIY9qhnvYNZDEZu9aUU9t7?usp=drive_link',
    NULL),
(69,
    'Murud',
    'Dapoli',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1u6QIzHwEqgZl9cpSbWW_gPE54ffWiPaq?usp=drive_link',
    NULL),
(70,
    'Vanand Village',
    'Dapoli',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/13u-zveHOu3McbwHD9xmgUUU1jjpV3VrK?usp=drive_link',
    NULL),
(71,
    'Nageshwar temple, Chorvane',
    'Khed',
    'Nageshwar ,Choravane,Tal.Khed Maharashtra 415718, India',
    NULL,
    'https://www.instagram.com/reel/CuPRONzgynE/?utm_',
    'Ancient Shiva temple surrounded by greenery; peaceful riverside atmosphere. Popular among locals for darshan, meditation, and Shivratri visits.',
    'Old heritage temple, calm surroundings, spiritual ambience',
    '09:00 AM to 05:00 PM',
    NULL,
    'https://drive.google.com/drive/folders/1jS-0NQ4nRLMTMgXGSwhpKPNPMK6ewPuX?usp=drive_link',
    NULL),
(72,
    'Shree ramvardayani mandir, chorvane',
    'Khed',
    'Chorvane village, Tal.Khed, Ratnagiri district, Maharashtra (Konkan region)',
    NULL,
    'https://www.youtube.com/shorts/-HX_O_n7cxM',
    'Local temple — likely of regional importance; potential for rural-temple ambience and insight into local religious/cultural life.',
    'Village temple, rural Konkan culture, authentic local experience',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1n4hJABGsWXJ7YRJR4V4tu70E87-7zUyt?usp=drive_link',
    NULL),
(73,
    'Kartel',
    'Khed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1qRxIRnca1YLa6a6Cy15e3NIDy3uMZfBV?usp=drive_link',
    NULL),
(74,
    'Wadibeldar',
    'Khed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1UGa_aQ1_leYUAyIhIwmbgVk_H4KyOIgv?usp=drive_link',
    NULL),
(75,
    'Songaon Mangrove Ecotourism & Crocodile Safari',
    'Khed',
    'Songav, Tal, Khed, Maharashtra 415722, India',
    NULL,
    'https://www.instagram.com/reel/DDFCXlTzt_L/?utm_',
    'Good for rural tourism, nature walks, small temples, local culture & village life experiences. Offers peaceful, non-touristy environment.',
    'Peaceful environment, village lifestyle, and access to nearby Khed attractions.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1XDB1vfUYhUprFzwJZkWoppWQ1OG4-9HV?usp=drive_link',
    NULL),
(76,
    'Bhuleshwar Shiva Temple, Furus Khed',
    'Khed',
    'Furus Village, Khed Taluka, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/ChbXvQaov4Z/?utm_',
    'A small old Shiva temple located in a calm forested area of Furus. Known for its peaceful atmosphere, local devotion, and typical Konkan stone-temple style. Good for a quiet spiritual stop.',
    'Local Shiva temple; calm ambience; village-side spiritual point',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1BjzQXUlDc-NiTC9Gx48LpOipEHWGllR3?usp=drive_link',
    NULL),
(77,
    'Mahipatgad',
    'Khed',
    'East of Khed Taluka, near the Rasalgad–Sumargad mountain range in Maharashtra.',
    NULL,
    'https://www.instagram.com/p/C14OZBkJRv3/?utm_',
    'One of the tallest and largest forts in the region, spread across 120 acres. It has natural cliff protection, remains of six ancient gates, a large Pareshwar Temple, and a freshwater well. Built and repaired during Shivaji Maharaj’s era.',
    'Hill fort trek, historical significance, Pareshwar Temple, scenic views, and connection to Shivaji Maharaj & Ramdas Swami.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Sb_ORRm5yUuVawHy8fJz9Kvdd5cMUGbT?usp=drive_link',
    NULL),
(78,
    'Sumargad',
    'Khed',
    'Wadi – Jaitapur region, Khed Taluka, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/CxmlHgBo1Xy/?utm_',
    'One of the least explored treks in Ratnagiri. Offers rocky patches, lush greenery, cliff views, forest trails & raw Konkan wilderness. Suitable for trekkers who enjoy offbeat, non-commercial trails.',
    'Offbeat trek, views of surrounding Sahyadri ranges, dense forest route, peaceful summit, no commercialization',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1kWvIVvWHaDeZ5keuaHVxxLodRSzo81D2?usp=drive_link',
    NULL),
(79,
    'Rasalgad',
    'Khed',
    'Khed Taluka, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DJtuquvobAT/?utm_',
    'Historic Maratha-era fort once captured by Chhatrapati Shivaji Maharaj (from the More clan of Javli).Scenic views: you can see neighbouring forts Suamargad and Mahipatgad from Rasalgad — forming a triangular-spur of forts.',
    'Easy trek + historic ambiance + temple + old fort architecture — good for beginners, families, and heritage-lovers.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1cBNhdFK9kvAmvUsIZJu4AhjMcPoHoVpF?usp=drive_link',
    NULL),
(80,
    'Paldurg Fort',
    'Khed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1kUFO7uPV_Fap45qvWK-p3P9mG79AjUT8?usp=drive_link',
    NULL),
(81,
    'Raghuveer Ghat',
    'Khed',
    'Khed Taluka, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.youtube.com/shorts/Hz43FluXgj8',
    'The ghat lies roughly 1,400 m above sea level, in the lap of the Sahyadri Range — surrounded by lush green hills, forests and seasonal waterfalls.The area also forms part of a biologically rich zone — home to rare species such as the freshwater crab Gubernatoriana thackerayi, first recorded here.',
    'Scenic natural beauty — hills, forests, waterfalls and misty landscapes.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Q0OyvP7atGJKdqT6W6wC2LHGF3vQkcGV?usp=drive_link',
    NULL),
(82,
    'Caves at Khed',
    'Khed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1ifnj4c0yhBkkxc49Vs65SUQ7My8Skq4F?usp=drive_link',
    NULL),
(83,
    'Shri Kalkai Temple (Bharane)',
    'Khed',
    'Bharane village, Taluka Khed, Ratnagiri district, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DO6L-TcjEOC/?utm_',
    'Local village-temple of Kalkai Devi. Temple premises, village ambience — good for spiritual visit and village-level Konkan culture.',
    'Local/folk temple — possibly visited by locals; may offer rural Konkan-temple experience',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/13KQbCnZOpopl3I4EncQ2JaC-bUKBhEL7?usp=drive_link',
    NULL),
(84,
    'Niribaji Waterfall (Khandoshi Village)',
    'Khed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/16vYYpaoystMxiI-lVNEjh381-LyohASz?usp=drive_link',
    NULL),
(85,
    'Anari',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/10UUSngeR7ptKlqCUiK_MsIQBzcKdsnh3?usp=drive_link',
    NULL),
(86,
    'Dalwatne',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1zNsCVaOIgrc4TaNbhH9KvFbPtgS8EgkW?usp=drive_link',
    NULL),
(87,
    'Gandhareshwar',
    'Chiplun',
    'Muradpur, Chiplun, Maharashtra 415605, India.',
    NULL,
    'https://www.instagram.com/reel/DQIywmWEx1x/?igsh=',
    'Good for religious/cultural visit; may also reflect local village/town heritage and architecture.',
    'Local-temple heritage, community worship, potential traditional festivals / rituals',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1bqf_E7FR5mcLlEHZgPthu4y4I9LDmVZ_?usp=drive_link',
    NULL),
(88,
    'Adare',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Xx00jh1w3SAl0u7M-oMVlbOaAoDumQUp?usp=drive_link',
    NULL),
(89,
    'Goval Kot Fort',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1O_qL4rReqVx7VwAWUoAvjF2ho0RZNdKM?usp=drive_link',
    NULL),
(90,
    'Kolkewadi Durg',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1i14cngMpEao6jGl8MX9reelqIL8LLGQ-?usp=drive_link',
    NULL),
(91,
    'Bhairavgad',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1aspsQW4LYEjuB_MZWzBFUJRu01iW-0rn?usp=drive_link',
    NULL),
(92,
    'Derwan',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1H3vOyysLQgGEuSrJM3qrIYxPmQ9_QLNM?usp=drive_link',
    NULL),
(93,
    'Sawatsada Waterfall',
    'Chiplun',
    'Near Parshuram Ghat, NH-66 Highway, Chiplun, Ratnagiri District, Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DNk3hWCypDp/?utm_source=ig_web_button_share_sheet',
    'A popular seasonal waterfall visible right from the highway near Parshuram Ghat. Becomes huge & powerful in monsoon. Easy to access, perfect for photography, a quick stopover, and enjoying misty valley views.',
    'Highway waterfall, monsoon hotspot, roadside viewpoint, safe & easy access',
    'Sapteshwar temple',
    NULL,
    'https://drive.google.com/drive/folders/1HozG8llRsDsC8aTGY0-QfKKi_ZfL7d4z?usp=drive_link',
    NULL),
(94,
    'Sharada Devi Temple (Turambav)',
    'Chiplun',
    'Turambav, Chiplun, Ratnagiri 415641, Maharashtra.',
    NULL,
    'https://www.youtube.com/shorts/ytZfMMroTlw',
    'The temple architecture is notable built in a Rajasthani style, with carved marble stones, a dome-shaped chautara (central pavilion), and multiple deities: besides the main idol of Sharada Devi, there are idols of village-goddesses like Vardayini, Manai, and Chandika. A popular seasonal waterfall visible right from the highway near Parshuram Ghat. Becomes huge & powerful in monsoon. Easy to access, perfect for photography, a quick stopover, and enjoying misty valley views.',
    'Spiritual ambiance, Sharda Devi idol, festivals, and scenic temple surroundings.',
    '6:00 AM – 6:00 PM',
    NULL,
    'https://drive.google.com/drive/folders/1-JUTzDgLuQSs0ja6fdvkfRcvQ0xNCAvY?usp=drive_link',
    NULL),
(95,
    'Kulswamini Bhavani Waghjai Temple (Terev)',
    'Chiplun',
    'Terav village, Taluka Chiplun, District Ratnagiri, Maharashtra — PIN 415605',
    NULL,
    'https://www.instagram.com/reel/DPLHvUCkc_T/?utm_',
    'The main idol of Goddess Bhawani is a black-stone statue about 9 ft tall, holding weapons and symbolising the defeat of the demon. It’s the only temple in Maharashtra where all nine forms of Goddess Navadurga are installed. Strong cultural and local significance: devotees come especially during festivals.',
    'For peace, greenery and good weather — post-monsoon and winter months are ideal, when the surrounding hills and village look very scenic.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Xihh96rB10EdMcbamLBF4svK25n1OZ5S?usp=drive_link',
    NULL),
(96,
    'Devi Karanjeshwari Temple (Goval Kot)',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1BU4Q1iadsSJuc1mgbAiIatxsw_gSQtqB?usp=drive_link',
    NULL),
(97,
    'Pandav-era Caves, Peer Baba Dargah',
    'Chiplun',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1pmAx4caiBAisjq6yGoi7ZR4R8Ak1P5Xp?usp=drive_link',
    NULL),
(98,
    'Vijaygad',
    'Guhagar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1DG5m1wmPBcNpxBx4p-DG12j1kI05yQzd?usp=drive_link',
    NULL),
(99,
    'Modka Depot',
    'Guhagar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1iUVrKrTC0nQA9CEh2hBITl4MZrWHk1N_?usp=drive_link',
    NULL),
(100,
    'Durga Devi Temple (Budhal)',
    'Guhagar',
    NULL,
    NULL,
    'https://www.youtube.com/shorts/XSe8dL5l4xY',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1IMX-apoaKUFCtwGaAsPGXg8fHa3nfV99?usp=drive_link',
    NULL),
(101,
    'Kotaluk',
    'Guhagar',
    NULL,
    NULL,
    'https://www.instagram.com/reel/DQokr_kjGSR/?utm_',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1b7LlGK4Pd20EELBbPJtO3O0svjQAruHk?usp=drive_link',
    NULL),
(102,
    'Varaveli- Vervali',
    'Guhagar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/159z_PtojkIcOxWlEUF79mf9HkfVy171W?usp=drive_link',
    NULL),
(103,
    'Sakhari Depot',
    'Guhagar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Oi2nmYVvNl1LyFS5-nDgTB9KSpLaSS0B?usp=drive_link',
    NULL),
(104,
    'Shirgaon',
    'Guhagar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1rAbAeybNwBOQFXBLU88xHxJJqknw5ivb?usp=drive_link',
    NULL),
(105,
    'Bhavanigad',
    'Sangameshwar',
    NULL,
    NULL,
    'https://www.youtube.com/watch?v=uBi8O-OApIQ',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1VTylcXPnvJrjaGS0COQzbodqNhBZscjp?usp=drive_link',
    NULL),
(106,
    'Prachitgad',
    'Sangameshwar',
    NULL,
    NULL,
    'https://www.instagram.com/reel/DQst8B6jF7L/?igsh=',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1cAnFbd6lPQtwxUisHL9D6ZXn4ce6Kj3q?usp=drive_link',
    NULL),
(107,
    'Mahipatgad',
    'Sangameshwar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1y4J53_OoDTZHMvgLURWRGvYH111DaTsA?usp=drive_link',
    NULL),
(108,
    'Shri Karneshwar Temple',
    'Sangameshwar',
    'Kasaba - Kalambaste Rd, 
Kasaba, Wada Thikanat, 
Sangameshwar,
Ratnagiri,
Maharashtra',
    NULL,
    'https://www.instagram.com/reel/DNGB_uhsCX-/?igsh=',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1ejiIGtU-r4ZfC-3h9qhrC2Q70SaeDoGX?usp=drive_link',
    NULL),
(109,
    'Machal',
    'Lanja',
    'Machal Village, Tal.Lanja, Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DKJGKVUzaBF/?utm_',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1cUzvzBM3tycSTD3gg1XURoFuqL4vHQPL?usp=drive_link',
    NULL),
(110,
    'Math',
    'Lanja',
    NULL,
    NULL,
    'https://www.youtube.com/shorts/R7soNPuu_wI',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1EPoD_wN9eitEamLko6zk7tPKQnEEbNgp?usp=drive_link',
    NULL),
(111,
    'Satavali Fort',
    'Lanja',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Cu537w54qRbs0y4zFh6y2KsPBdlc-NwY?usp=drive_link',
    NULL),
(112,
    'Rani Laxmibai Memorial (Mouje Kot)',
    'Lanja',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/173B1BBGm1jaDQsE5TEcm68iAXKcuMTKf?usp=drive_link',
    NULL),
(113,
    'Gangu’s Bowl (Bapere Zorewadi)',
    'Lanja',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1ZfhHUx_uB7bOM91Jmc2DwbtpQoXsAKP6?usp=drive_link',
    NULL),
(114,
    'Pawas',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1F4NeFU5hxU-1KJB0V0v3pK_MEaFugdfR?usp=drive_link',
    NULL),
(115,
    'Hatis',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1MuyowmOXSDXEy4kQtXVQ6hruxh7CWvnP?usp=drive_link',
    NULL),
(116,
    'Ratnagiri City',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1v14YyDnBbLVtcKi2HtS6mLXQLJj4ToJb?usp=drive_link',
    NULL),
(117,
    'Nirul',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Ek_KWbac-w0eSYjJdZvoKpzdxyViyk6X?usp=drive_link',
    NULL),
(118,
    'Nivali Waterfall',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Ftqj9yyz1IaPfqQtEYNtxypQc7_KTANQ?usp=drive_link',
    NULL),
(119,
    'Kalbadevi Temple and Beach',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1z_zeN7BFlYuk5uX4ZSK1Jjkk6sYyDOjq?usp=drive_link',
    NULL),
(120,
    'Shil Dam',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1L_lWqicjfs4PjXMyUnf-6tn91Zt5svLl?usp=drive_link',
    NULL),
(121,
    'Rantal',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1FBa-n4NoRVMXeASggCL6RPb9PRFC9D8_?usp=drive_link',
    NULL),
(122,
    'Dhopeshwar Temple',
    'Rajapur',
    'Dhopeshwar village, Tal. Rajapur, Dist. Ratnagiri',
    NULL,
    'https://www.instagram.com/reel/DK6Api5oUwx/?igsh=',
    'The sacred energy here truly makes you feel the presence of Lord Shambhu Mahadev. The temple premises also include shrines of Lord Dattatreya and Kalbhairav. The temple was recently renovated, using stone, wood, colours and lighting that recreate an atmosphere from 200–300 years ago. The sabhamandap (assembly hall) was added during the Peshwa era.',
    'During the monsoon, the scenery around the temple becomes extremely beautiful.',
    'July to November',
    NULL,
    'https://drive.google.com/drive/folders/1Yh-q3XV5LLafZ5k66jnOSYJvQUe20oIS?usp=drive_link',
    NULL),
(123,
    'Chunakolwan',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1MfOPUweBAgZ1Sjz-uZdbSnFXTxhdyj2I?usp=drive_link',
    NULL),
(124,
    'Yashwantgad',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1xTSQBOnZt_RCLnLJUYaB98JyRpc_EnzR?usp=drive_link',
    NULL),
(125,
    'Rajapur Fort',
    'Ratnagiri',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1tSG_Jbq1fkFbfOwWAzCRJ1r0yqPVQUCc?usp=drive_link',
    NULL),
(126,
    'Gangatirth & Hot Water Spring',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1b7rF4GXA4ljFsHF7tvjlUgfyFz62EIdK?usp=drive_link',
    NULL),
(127,
    'Rock Carvings (Rajapur Taluka)',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1V_2XSBiCM8Sgq07youGMcYXz75D4PspI?usp=drive_link',
    NULL),
(128,
    'Mouje Soundal',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1AvjEhXCoWYXHig7C1Hli88TGaxKoU8tw?usp=drive_link',
    NULL),
(129,
    'Ozar Waterfall (Ghagwadi)',
    'Rajapur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1SdeKR5cffx6nntUyfoXBWaaVTzQYqbfD?usp=drive_link',
    NULL),
(130,
    'Savatkada waterfall',
    'Rajapur',
    NULL,
    NULL,
    'https://www.instagram.com/reel/DK4kt12oXtF/?utm_',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1Y5uOA-JdnWyaiUyxLK-8M8bvduW9h55s?usp=drive_link',
    NULL),
(131,
    'Phansavle Bridge',
    'Ratnagiri',
    'Phansavle Village, Ratnagiri- 415612',
    NULL,
    'https://www.instagram.com/reel/DRWDdnwiGLZ/?utm_',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1re4bNbYG7TAxgIBVt1nRTmhG8V5OaFH5?usp=drive_link',
    NULL),
(132,
    'Patit Pavan Temple',
    'Ratnagiri',
    NULL,
    NULL,
    'https://www.instagram.com/reel/C70bLCdIYJY/?utm_',
    'Swatantryaveer Savarkar stayed in Ratnagiri for 16 years wherein he built Patit Pavan Temple. This temple was built for people who were considered untouchable or inferior. A man of any caste had an access to the innermost part (gabhara) of the temple. On the request of Savarkar, Mr. Bhagoji Sheth Keer built this temple by spending about ₹ 1.5 lakhs. This temple was completed in 1931.',
    'This temple of Laxmi and Vishnu is in the heart of the town of Ratnagiri in coastal Maharashtra. It was inaugurated in 1931 and is the first temple in India open to Hindus of all castes.',
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/1lPb_ElJOdhSUsHeEyruo1hJq5lJF6Bmb?usp=drive_link',
    NULL),
(133,
    'Mallika arjun temple',
    'Chiplun',
    NULL,
    NULL,
    'https://www.instagram.com/reel/DNOGRHUoG1f/?utm_',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/drive/folders/12h49Jby7mD_xDluYc7x6rrno-j4N2iT1?usp=drive_link',
    NULL);

-- Verify the data insertion
SELECT COUNT(*) as total_locations FROM tourist_locations;
SELECT taluka, COUNT(*) as location_count FROM tourist_locations GROUP BY taluka ORDER BY location_count DESC;

-- Sample queries to test the data
SELECT place_name, taluka, famous_for 
FROM tourist_locations 
WHERE taluka = 'Ratnagiri' 
ORDER BY sr_no 
LIMIT 5;
