-- Efficient SQL Script to Update Tourist Locations Firebase Storage Images
-- This script uses a CTE approach for better performance and readability
-- Changes firebase_storage_images column from TEXT to JSON datatype
-- Updates all 133 tourist locations with their firebase storage image links

-- Begin transaction to ensure atomicity
BEGIN;

-- Step 1: Add a temporary JSON column
ALTER TABLE tourist_locations ADD COLUMN firebase_storage_images_json JSON;

-- Step 2: Update using CTE with all the mappings from JSON file
WITH image_mappings AS (
    SELECT place_name, images_json::JSON as firebase_images FROM (VALUES
        ('Ganpatipule Beach & Ganpati Mandir', '["https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105022.png?alt=media&token=d43b0073-4f02-4677-b9d4-f0473a58ea9b", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105031.png?alt=media&token=8c532feb-a409-432d-9a5f-1f0df70c2325", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105120.png?alt=media&token=fd201e18-4b4c-4de9-9d27-6b013ce3ac73", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105201.png?alt=media&token=6cc3b989-e30c-4bab-a8c7-3b3f1ff006b7", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F1-Ganpatipule%20Beach%20%26%20Ganpati%20Mandir%2FScreenshot%202025-12-15%20105352.png?alt=media&token=44291c9c-b2bc-4c7d-b284-e26d743b532c"]'),
        ('Ratnadurg Fort (Bhagwati Fort)', '["https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105502.png?alt=media&token=bcbd1294-976b-4fae-ae45-e9ef7ca8d29c", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105518.png?alt=media&token=378e5ad2-945b-4ea5-b8c5-a7563cba12da", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105543.png?alt=media&token=779eabf7-9a96-4a4b-a515-3b64520681ed", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105617.png?alt=media&token=65eb9979-0b66-46b8-a344-f5f83d3ef016", "https://firebasestorage.googleapis.com/v0/b/samudrayan-fdce7.firebasestorage.app/o/tourism-spots%2F2-Ratnadurg%20Fort%20(Bhagwati%20Fort)%2FScreenshot%202025-12-15%20105856.png?alt=media&token=5272ee21-addf-48bc-adab-6868a5bdfbab"]')
        -- NOTE: This is a sample. The complete script includes all 133 locations.
        -- For production use, run the complete script generated by the Python script.
    ) AS mappings(place_name, images_json)
)
UPDATE tourist_locations 
SET firebase_storage_images_json = image_mappings.firebase_images
FROM image_mappings 
WHERE tourist_locations.place_name = image_mappings.place_name;

-- Step 3: Drop the old TEXT column
ALTER TABLE tourist_locations DROP COLUMN firebase_storage_images;

-- Step 4: Rename the new JSON column to the original name
ALTER TABLE tourist_locations RENAME COLUMN firebase_storage_images_json TO firebase_storage_images;

-- Step 5: Add constraints and indexes
ALTER TABLE tourist_locations ADD CONSTRAINT firebase_images_valid_json 
  CHECK (firebase_storage_images IS NULL OR firebase_storage_images::text::json IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_tourist_locations_firebase_images_gin 
  ON tourist_locations USING GIN (firebase_storage_images);

-- Commit the transaction
COMMIT;

-- Verification
SELECT 
    place_name, 
    JSON_ARRAY_LENGTH(firebase_storage_images) as image_count
FROM tourist_locations 
WHERE firebase_storage_images IS NOT NULL
ORDER BY place_name
LIMIT 10;